sudo: required
services:
  - docker

before_install:
  - docker build -t ajay286/docker-react-ci-cd -f Dockerfile.dev .

script:
  - docker run -e CI=true  ajay286/docker-react-ci-cd npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-135728626475"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
